---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dell.
--- DateTime: 2020/11/24 下午6:04
---

local template = require "resty.template"
local _M = {}
function _M.index()
    local model = {title = "hello template", content = "<h1>content</h1>"}
    
    -- 1、外部模板文件
     template.render("/index.html", model)
    -- 2、内嵌模板代码
--    template.render([[
--<html>
--<head>
--    <meta charset="UTF-8">
--    <title>{{ title }}</title>
--</head>
--<body>
--    {* content *}
--</body>
--</html>
--        ]], model)

end
return _M