---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dell.
--- DateTime: 2020/11/24 下午6:04
---

local template = require "resty.template"
local postman = require("cus.postman")

local _M = {}
local function Parse()
    local model = {}
    local request_method = ngx.var.request_method
    local args = nil
    local Body = nil
    local CurTime = nil
    local CheckSum = nil
    local MD5 = nil
    local host = nil
    if "GET" == request_method then
        args = ngx.req.get_uri_args()
    elseif "POST" == request_method then
        ngx.req.read_body()
        --获取post请求的参数
        local post_args_tab = ngx.req.get_post_args()
        for k, v in pairs(post_args_tab) do
            model[k]=v
        end
        Body = ngx.req.get_body_data()
    end
    model["resp"] = postman.httpPost(model["reqUrl"], model["reqBody"])
    return model
end
function _M.index()
    local model = Parse()
    -- 1、外部模板文件
     template.render("/index.html", model)

end
return _M