---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by dell.
--- DateTime: 2020/11/24 下午5:49


util = {}

string.split = function(s, p)
    local rt= {}
    string.gsub(s, '[^'..p..']+',
            function(w)
                table.insert(rt, w)
            end )
    return rt
end

--通过解析main.go来获取算法列表
function util.getPsdList(filename)
    local file = io.open(filename, "r")
    local psdlist = {}
    for line in io.lines(filename) do

        if  #line <= 0 or string.find(line, "SetMember") == nil then
            goto continue
        end

        local rt = string.split(line, ',')
        if #rt <= 0 or #rt[1] == 0 then
            goto continue
        end

        local rt1 = string.split(rt[1],'(')
        if  #rt <=1 or #rt1[2] == 0 then
            goto continue
        end

        local rt2 = string.split(rt1[2],'\"')
        if  #rt <= 0 or #rt2[1] == 0 then
            goto continue
        end
        table.insert(psdlist, rt2)
        ::continue::
    end
    file:close()
    return psdlist
end


--table 长度计算
function util.table_leng(t)
    local leng=0
    for k, v in pairs(t) do
        leng=leng+1
    end
    return leng;
end
return util